# Generated by Django 3.1.7 on 2021-04-09 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roboworld_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name_text',
            new_name='nombre',
        ),
    ]
